## Name: jariwala Mohit S.
## Reg. No: 2548563
## Sub: DL
## Program: 2. Next Word Predictore through LSTM

In [37]:
# Data Upload & Preprocessing
Docs = "The India AI Impact Summit 2026, held from February 16–21, 2026, at Bharat Mandapam, New Delhi, was a major global event focused on AI for social good, governance, and infrastructure. Inaugurated by Prime Minister Narendra Modi, it highlighted India's role as a leading AI hub for the Global South, with significant investments from global tech majors"

In [38]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [39]:
tokenizer = Tokenizer()

In [40]:
tokenizer.fit_on_texts([Docs])

In [41]:
#Assigned numbers or integer to al the words present in the sentences.
tokenizer.word_index

{'ai': 1,
 'global': 2,
 'the': 3,
 '2026': 4,
 'from': 5,
 'a': 6,
 'for': 7,
 'india': 8,
 'impact': 9,
 'summit': 10,
 'held': 11,
 'february': 12,
 '16–21': 13,
 'at': 14,
 'bharat': 15,
 'mandapam': 16,
 'new': 17,
 'delhi': 18,
 'was': 19,
 'major': 20,
 'event': 21,
 'focused': 22,
 'on': 23,
 'social': 24,
 'good': 25,
 'governance': 26,
 'and': 27,
 'infrastructure': 28,
 'inaugurated': 29,
 'by': 30,
 'prime': 31,
 'minister': 32,
 'narendra': 33,
 'modi': 34,
 'it': 35,
 'highlighted': 36,
 "india's": 37,
 'role': 38,
 'as': 39,
 'leading': 40,
 'hub': 41,
 'south': 42,
 'with': 43,
 'significant': 44,
 'investments': 45,
 'tech': 46,
 'majors': 47}

In [42]:
len(tokenizer.word_index)

47

In [43]:
# Now review sentence by sentence and create the integer values in sequence for all the given sentences in input data, For that first we find the each sentence in the dataset.
for sentence in Docs.split(','):
    print(sentence)
    print(tokenizer.texts_to_sequences([sentence])[0])

The India AI Impact Summit 2026
[3, 8, 1, 9, 10, 4]
 held from February 16–21
[11, 5, 12, 13]
 2026
[4]
 at Bharat Mandapam
[14, 15, 16]
 New Delhi
[17, 18]
 was a major global event focused on AI for social good
[19, 6, 20, 2, 21, 22, 23, 1, 7, 24, 25]
 governance
[26]
 and infrastructure. Inaugurated by Prime Minister Narendra Modi
[27, 28, 29, 30, 31, 32, 33, 34]
 it highlighted India's role as a leading AI hub for the Global South
[35, 36, 37, 38, 39, 6, 40, 1, 41, 7, 3, 2, 42]
 with significant investments from global tech majors
[43, 44, 45, 5, 2, 46, 47]


In [44]:
tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
for i in range(1,len(tokenized_sentence)):
    print(tokenized_sentence[:i+1])

[43, 44]
[43, 44, 45]
[43, 44, 45, 5]
[43, 44, 45, 5, 2]
[43, 44, 45, 5, 2, 46]
[43, 44, 45, 5, 2, 46, 47]


In [45]:
input_sequences =[]
for sentence in Docs.split('.'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1]) # Collect the sequences
    print(tokenized_sentence[:i+1])

[3, 8]
[3, 8, 1]
[3, 8, 1, 9]
[3, 8, 1, 9, 10]
[3, 8, 1, 9, 10, 4]
[3, 8, 1, 9, 10, 4, 11]
[3, 8, 1, 9, 10, 4, 11, 5]
[3, 8, 1, 9, 10, 4, 11, 5, 12]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6, 20]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6, 20, 2]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6, 20, 2, 21]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6, 20, 2, 21, 22]
[3, 8, 1, 9, 10, 4, 11, 5, 12, 13, 4, 14, 15, 16, 17, 18, 19, 6, 20, 2, 21, 22, 23]
[3, 8, 1, 9, 10, 4, 

In [46]:
# calculate the length of the maximum sequence present.
maximum_length = max([len(x) for x in input_sequences])

In [47]:
# Do padding
from tensorflow.keras.utils import pad_sequences
padded_sequences = pad_sequences(input_sequences, maxlen = maximum_length, padding ='pre')
display(padded_sequences)

array([[ 0,  0,  0, ...,  0,  3,  8],
       [ 0,  0,  0, ...,  3,  8,  1],
       [ 0,  0,  0, ...,  8,  1,  9],
       ...,
       [ 0,  0,  0, ..., 45,  5,  2],
       [ 0,  0,  0, ...,  5,  2, 46],
       [ 0,  0,  0, ...,  2, 46, 47]], dtype=int32)

In [48]:
# Now split the input and output from the padded sequences
#now input of padded sequences will have all the word integers except last one in each row.
X = padded_sequences[:,:-1]
display(X)

array([[ 0,  0,  0, ...,  0,  0,  3],
       [ 0,  0,  0, ...,  0,  3,  8],
       [ 0,  0,  0, ...,  3,  8,  1],
       ...,
       [ 0,  0,  0, ..., 44, 45,  5],
       [ 0,  0,  0, ..., 45,  5,  2],
       [ 0,  0,  0, ...,  5,  2, 46]], dtype=int32)

In [49]:
#Similarly, for the output
y = padded_sequences[:, -1]
display(y)

array([ 8,  1,  9, 10,  4, 11,  5, 12, 13,  4, 14, 15, 16, 17, 18, 19,  6,
       20,  2, 21, 22, 23,  1,  7, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39,  6, 40,  1, 41,  7,  3,  2, 42, 43, 44, 45,  5,
        2, 46, 47], dtype=int32)

In [50]:
# Now, Predicting the output wil be in classification task. So, converting the integer values in One hot encoded vector.
X.shape

(54, 29)

In [51]:
y.shape

(54,)

In [52]:
from tensorflow.keras.utils import to_categorical
to_categorical(y, num_classes = len(tokenizer.word_index)+1)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
y = to_categorical(y, num_classes = len(tokenizer.word_index)+1)
y.shape

(54, 48)

In [54]:
#Architecture of LSTM
#THREE LAYERS
# 1. Embedding layer 2. LSTM Layer 3. Dense Layer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [59]:
model = Sequential()
model.add(Embedding(len(tokenizer.word_index)+1, 10))
model.add(LSTM(100))
model.add(Dense(len(tokenizer.word_index)+1, activation = 'softmax'))

In [60]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [64]:
model.build(input_shape=(None, maximum_length-1)) # (batch_size, input_length)
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 29, 10)         │           480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 100)            │        44,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 48)             │         4,848 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 49,728 (194.25 KB)

 Trainable params: 49,728 (194.25 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
model.fit(X,y,epochs=150)

Epoch 1/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5559 - loss: 1.7501
Epoch 2/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4232 - loss: 1.7873
Epoch 3/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4232 - loss: 1.8363
Epoch 4/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2951 - loss: 1.8441
Epoch 5/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5104 - loss: 1.7674
Epoch 6/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5521 - loss: 1.6595
Epoch 7/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6366 - loss: 1.5771
Epoch 8/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6177 - loss: 1.5954
Epoch 9/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5019 - loss: 1.6165
Epoch 10/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7296 - loss: 1.5215
Epoch 11/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7315 - loss: 1.5067 
Epoch 12/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7106 - l

In [80]:
import numpy as np

text = "significant"
# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text = pad_sequences([token_text], maxlen=maximum_length-1, padding='pre')
#predict
position = np.argmax(model.predict(padded_token_text))

for word,index in tokenizer.word_index.items():
    if index == position:
        print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
india
